### ISSUE TITLE
code building problem

### ISSUE THREAD

**Issue by AlphaMTV** [timothybrooks/hdr-plus#1]
Hi, Tim,

We try to compile the codes and find some problems with the Halide part.
We want to know what version of Halide used in the compilation of your codes,
so we can download the correct one.

Could you kindly provide the info?

Thank you

**Comment by timothybrooks** [comment]
AlphaMTV,

Thanks for reaching out. I do not have the version number off hand, and have slightly limited access right now because I am on vacation. However, here is a build that I used during testing: https://cmu.app.box.com/s/z09bbnlc0adjrsh5w4eqng0vm5rxd07h. The source is included, so you could build directly from this, but you may prefer deducing the version number and downloading the source from the Halide repo.

@suhaasr response on the other thread also gives our time frame and useful instructions for how to build Halide from source.

Alternatively, feel free to suggest fixes to our HDR+ implementation such that it works atop the current Halide version! We would love to keep things up-to-date, and the changes likely would not be too significant. If you go this route, please commit the fixes back to our repo!

Best,

Tim Brooks
