### ISSUE TITLE
Corrupted Image

### ISSUE THREAD

**Issue by diwersan7** [timothybrooks/hdr-plus#12]
I get corruption like this as a result:
![image](https://user-images.githubusercontent.com/13134670/39665070-4c15a942-5064-11e8-9e20-7e7676c49d11.png)
Any suggestions?

**Comment by timothybrooks** [comment]
Could you please provide the input images as well?

**Comment by timothybrooks** [comment]
The strange results are because this pipeline is designed to work on a burst of photographs that are all taken at the _same_ (under)exposure. For more details on why this is the case, please refer to the [original paper](http://www.hdrplusdata.org/hdrplus.pdf) or [my writeup](http://timothybrooks.com/tech/hdr-plus/).
