### ISSUE TITLE
pink image result of .DNG image format? 

### ISSUE THREAD

**Issue by zhouxingguang** [timothybrooks/hdr-plus#25]
I use the ".DNG" format to test the code, and the result is a pink image(the width is bigger than height). Is anyone knows why?
By the way, the result of image format ".CR" is okay.

**Comment by timothybrooks** [comment]
The issue is due to incorrect black and/or white levels. I used constants for the black and white levels (as well as other parameters, such as image size) of my Canon 5D III. For use with other raw images, make sure you change these values accordingly.

You can use dcraw to find the black and white levels of your camera if you do not already know them. If your camera has insufficient metadata, and dcraw is unable to attain these values, you can simply capture completely black and completely white photographs, and get an approximate value that way.

Ideally, the pipeline would be updated to read these directly from dcraw. I am no longer maintaining the code due to a conflict of interest, but I would be happy to accept a pull request that does this.
