### ISSUE TITLE
[make] no match function,template argument deduction/substitution failed

### ISSUE THREAD

**Issue by xzg-wang-er** [timothybrooks/hdr-plus#79]
![image](https://user-images.githubusercontent.com/16589506/146641177-83302da1-a4aa-40da-ba60-f9f47e6c66fc.png)

**Comment by AmberCheng** [comment]
hi, I have met the same problem. I wonder how you fix it?

**Comment by teboli** [comment]
Hi, 

I ran into the same problem. It is because in the meantime Halide itself changed the signature of its boundary functions. Now you should be using the Range object defined in Halide.h, that defines a slice between min and max (like [min:max] in Python) as:

 Func imgs_mirror = BoundaryConditions::mirror_interior(imgs, {Range(0, width), Range(0, height)});
 instead of the former
 Func imgs_mirror = BoundaryConditions::mirror_interior(imgs, 0, width, 0, height);
 
 Do it anywhere there is a call of boundary routines and it should not raise errors anymore. Hope it helps!

**Comment by Titaniumtown** [comment]
Fixed in #84
